name:                vortaro
version:             0.1.0.0
github:              "michaelvessia/vortaro"
license:             GPL-3
author:              "Michael Vessia"
maintainer:          "michaelvessia@gmail.com"
copyright:           "2018 Michael Vessia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/michaelvessia/vortaro#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  vortaro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vortaro

tests:
  vortaro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vortaro
